replicaCount: 4

image:
  repository: paranid5/app_piton
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {piton}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8082
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: paranid5.app_piton.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: config-volume
    configMap:
      name: app-config

volumeMounts:
  - name: config-volume
    mountPath: "/data/config.json"
    subPath: "config.json"
    readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

config:
  path: "files/config.json"
