name: CI (Flutter)

on:
  push:
    paths:
      - 'app_dart/**'
      - '.github/workflows/flutter.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app_dart

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .dart_tool/
            .pub-cache/
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyzer & Linter
        run: flutter analyze

      - name: Perform code generation via build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Tests
        run: flutter test --platform chrome

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./app_dart
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_dart:latest